### ISSUE TITLE
_

### ISSUE THREAD

**Issue by ghost** [mayflower/cordova-android-movetasktoback#1]
_

**Comment by DirtyHairy** [comment]
Hi Tomas!

I can install and use the plugin without issues. What cordova version are you using? Can you still reproduce this (or might it have been NPM hickup)?

Cheers
-Christian

**Comment by seomaton** [comment]
Hello Christian,

1. The latest cordova.
2. Yes. No NPM hiccup.

Cheers,
T

**Comment by seomaton** [comment]
It may be a different issue though. Put it on hold for the moment please.

**Comment by seomaton** [comment]
Fixed.
I had to rebuild the whole android platform.
My apologies for bothering you, Christian.
Please remove this whole issue.
Cheers,
T

**Comment by DirtyHairy** [comment]
Hi Tomas!

No worries, thanks for letting me know :smirk:

Cheers
-Christian

**Comment by seomaton** [comment]
It works perfectly, Christian. Where could I donate for this plugin, please? Let me know to t@qc.io
