### ISSUE TITLE
Plugin id should match npm module

### ISSUE THREAD

**Issue by perrin4869** [mayflower/cordova-android-movetasktoback#2]
The id in https://github.com/mayflower/cordova-android-movetasktoback/blob/master/plugin.xml, `cordova-plugin-android-movetasktoback`, does not match the npm module, `cordova-android-movetasktoback` which confuses cordova when saving modules to `config.xml`, installing modules, etc. Maybe the solution is to change the id? Or republish to npm as `cordova-plugin-android-movetasktoback`?

**Comment by DirtyHairy** [comment]
Hi Julian!

Can you describe more concisely  what issues the ID mismatch is causing for you? The mismatch is purely historical, and while I am certainly willing to do something about it if it causes any "real" issues, I don't want to screw existing users over aesthetics :smirk:

Cheers
     -Christian

**Comment by perrin4869** [comment]
Well, the problem is when you do `cordova plugin add --save cordova-android-movetasktoback` - the plugin is saved into `config.xml` as `cordova-plugin-android-movetasktoback` which is the plugin id. Later when you attempt to reinstall the plugin, it will fail to download it because it looks for the `cordova-plugin-android-movetasktoback` npm package which doesn't exist.
I'm not sure what the best solution is here. Maybe just changing the `id` will not even break any projects?

**Comment by DirtyHairy** [comment]
Ouch, this is a cordova bug. Have you reported it upstream? Nevertheless, I'll try to come up with a solution from my end :smirk:

**Comment by perrin4869** [comment]
I didn't report this upstream but I'm also not sure this is a bug. Maybe they want to enforce a plugin id and npm pairing match.

There is some more info here: https://cordova.apache.org/announcements/2015/04/21/plugins-release-and-move-to-npm.html

**Comment by perrin4869** [comment]
@DirtyHairy any updates on this? I think just changing the plugin id from `cordova-plugin-android-movetasktoback` to `cordova-android-movetasktoback` will fix the issue without breaking current users. Can't be 100% sure though

**Comment by DirtyHairy** [comment]
Hi @perrin4869 !

Sorry, I basically forgot about this issue, thanks for the bump. I'll check out your suggestion.

Cheers
    -Christian

**Comment by perrin4869** [comment]
@DirtyHairy before changing the ID and publishing, you should send a PR to [Cordova Registry Mapper](https://github.com/stevengill/cordova-registry-mapper) mapping the old ID to the new ID. Then you could publish the new plugin id without problem imo.
Check this for more info: https://cordova.apache.org/announcements/2015/04/21/plugins-release-and-move-to-npm.html

**Comment by perrin4869** [comment]
@DirtyHairy don't wanna be a nuisance, but did you get around to checking my suggestion?

**Comment by DirtyHairy** [comment]
You're not a nuisance, you are as patient as am a sloth :turtle: :smirk: Thanks for nagging, I promise to look at it this weekend.

**Comment by DirtyHairy** [comment]
Fixed in Release 0.1.4. Sorry again for putting this off for so long, and thanks alot to @fdezRomero for his PR.
